minimal:
    image: likol1227/php7
    ports:
        - "8080:8000"
    volumes:
        - ./minimal:/app
    working_dir: /app
    command: "php -S 0.0.0.0:8000"

micro:
    image: likol1227/php7
    ports:
        - "8081:8000"
    volumes:
        - ./micro:/app
    working_dir: /app
    command: "php -S 0.0.0.0:8000"
